services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dreamjournal
      POSTGRES_PASSWORD: dreamjournal
      POSTGRES_DB: dreamjournal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dreamjournal"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      DATABASE_URL: "postgres://dreamjournal:dreamjournal@postgres:5432/dreamjournal?sslmode=disable"
      PORT: "50051"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
