// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: dream_journal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DreamJournal_Register_FullMethodName       = "/dreamjournal.DreamJournal/Register"
	DreamJournal_Login_FullMethodName          = "/dreamjournal.DreamJournal/Login"
	DreamJournal_CreateDream_FullMethodName    = "/dreamjournal.DreamJournal/CreateDream"
	DreamJournal_ListDreams_FullMethodName     = "/dreamjournal.DreamJournal/ListDreams"
	DreamJournal_SummarizeDream_FullMethodName = "/dreamjournal.DreamJournal/SummarizeDream"
	DreamJournal_DreamProphecy_FullMethodName  = "/dreamjournal.DreamJournal/DreamProphecy"
	DreamJournal_TagDream_FullMethodName       = "/dreamjournal.DreamJournal/TagDream"
	DreamJournal_GetAIInsights_FullMethodName  = "/dreamjournal.DreamJournal/GetAIInsights"
)

// DreamJournalClient is the client API for DreamJournal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DreamJournal service definition
type DreamJournalClient interface {
	// Register creates a new user account
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Login authenticates a user
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// CreateDream creates a new dream entry
	CreateDream(ctx context.Context, in *DreamRequest, opts ...grpc.CallOption) (*DreamResponse, error)
	// ListDreams streams dreams based on the request parameters
	ListDreams(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Dream], error)
	// SummarizeDream summarizes a dream using OpenAI
	SummarizeDream(ctx context.Context, in *DreamRequest, opts ...grpc.CallOption) (*DreamSummary, error)
	// DreamProphecy generates a mystical prophecy from a dream
	DreamProphecy(ctx context.Context, in *DreamRequest, opts ...grpc.CallOption) (*ProphecyResponse, error)
	// TagDream extracts tags from a dream using OpenAI
	TagDream(ctx context.Context, in *DreamRequest, opts ...grpc.CallOption) (*TagResponse, error)
	// GetAIInsights streams AI insights for a user's dreams
	GetAIInsights(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DreamInsight], error)
}

type dreamJournalClient struct {
	cc grpc.ClientConnInterface
}

func NewDreamJournalClient(cc grpc.ClientConnInterface) DreamJournalClient {
	return &dreamJournalClient{cc}
}

func (c *dreamJournalClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, DreamJournal_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dreamJournalClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, DreamJournal_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dreamJournalClient) CreateDream(ctx context.Context, in *DreamRequest, opts ...grpc.CallOption) (*DreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DreamResponse)
	err := c.cc.Invoke(ctx, DreamJournal_CreateDream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dreamJournalClient) ListDreams(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Dream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DreamJournal_ServiceDesc.Streams[0], DreamJournal_ListDreams_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListRequest, Dream]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DreamJournal_ListDreamsClient = grpc.ServerStreamingClient[Dream]

func (c *dreamJournalClient) SummarizeDream(ctx context.Context, in *DreamRequest, opts ...grpc.CallOption) (*DreamSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DreamSummary)
	err := c.cc.Invoke(ctx, DreamJournal_SummarizeDream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dreamJournalClient) DreamProphecy(ctx context.Context, in *DreamRequest, opts ...grpc.CallOption) (*ProphecyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProphecyResponse)
	err := c.cc.Invoke(ctx, DreamJournal_DreamProphecy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dreamJournalClient) TagDream(ctx context.Context, in *DreamRequest, opts ...grpc.CallOption) (*TagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagResponse)
	err := c.cc.Invoke(ctx, DreamJournal_TagDream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dreamJournalClient) GetAIInsights(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DreamInsight], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DreamJournal_ServiceDesc.Streams[1], DreamJournal_GetAIInsights_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserRequest, DreamInsight]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DreamJournal_GetAIInsightsClient = grpc.ServerStreamingClient[DreamInsight]

// DreamJournalServer is the server API for DreamJournal service.
// All implementations must embed UnimplementedDreamJournalServer
// for forward compatibility.
//
// DreamJournal service definition
type DreamJournalServer interface {
	// Register creates a new user account
	Register(context.Context, *RegisterRequest) (*AuthResponse, error)
	// Login authenticates a user
	Login(context.Context, *LoginRequest) (*AuthResponse, error)
	// CreateDream creates a new dream entry
	CreateDream(context.Context, *DreamRequest) (*DreamResponse, error)
	// ListDreams streams dreams based on the request parameters
	ListDreams(*ListRequest, grpc.ServerStreamingServer[Dream]) error
	// SummarizeDream summarizes a dream using OpenAI
	SummarizeDream(context.Context, *DreamRequest) (*DreamSummary, error)
	// DreamProphecy generates a mystical prophecy from a dream
	DreamProphecy(context.Context, *DreamRequest) (*ProphecyResponse, error)
	// TagDream extracts tags from a dream using OpenAI
	TagDream(context.Context, *DreamRequest) (*TagResponse, error)
	// GetAIInsights streams AI insights for a user's dreams
	GetAIInsights(*UserRequest, grpc.ServerStreamingServer[DreamInsight]) error
	mustEmbedUnimplementedDreamJournalServer()
}

// UnimplementedDreamJournalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDreamJournalServer struct{}

func (UnimplementedDreamJournalServer) Register(context.Context, *RegisterRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedDreamJournalServer) Login(context.Context, *LoginRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedDreamJournalServer) CreateDream(context.Context, *DreamRequest) (*DreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDream not implemented")
}
func (UnimplementedDreamJournalServer) ListDreams(*ListRequest, grpc.ServerStreamingServer[Dream]) error {
	return status.Errorf(codes.Unimplemented, "method ListDreams not implemented")
}
func (UnimplementedDreamJournalServer) SummarizeDream(context.Context, *DreamRequest) (*DreamSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SummarizeDream not implemented")
}
func (UnimplementedDreamJournalServer) DreamProphecy(context.Context, *DreamRequest) (*ProphecyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DreamProphecy not implemented")
}
func (UnimplementedDreamJournalServer) TagDream(context.Context, *DreamRequest) (*TagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagDream not implemented")
}
func (UnimplementedDreamJournalServer) GetAIInsights(*UserRequest, grpc.ServerStreamingServer[DreamInsight]) error {
	return status.Errorf(codes.Unimplemented, "method GetAIInsights not implemented")
}
func (UnimplementedDreamJournalServer) mustEmbedUnimplementedDreamJournalServer() {}
func (UnimplementedDreamJournalServer) testEmbeddedByValue()                      {}

// UnsafeDreamJournalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DreamJournalServer will
// result in compilation errors.
type UnsafeDreamJournalServer interface {
	mustEmbedUnimplementedDreamJournalServer()
}

func RegisterDreamJournalServer(s grpc.ServiceRegistrar, srv DreamJournalServer) {
	// If the following call pancis, it indicates UnimplementedDreamJournalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DreamJournal_ServiceDesc, srv)
}

func _DreamJournal_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DreamJournalServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DreamJournal_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DreamJournalServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DreamJournal_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DreamJournalServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DreamJournal_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DreamJournalServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DreamJournal_CreateDream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DreamJournalServer).CreateDream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DreamJournal_CreateDream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DreamJournalServer).CreateDream(ctx, req.(*DreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DreamJournal_ListDreams_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DreamJournalServer).ListDreams(m, &grpc.GenericServerStream[ListRequest, Dream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DreamJournal_ListDreamsServer = grpc.ServerStreamingServer[Dream]

func _DreamJournal_SummarizeDream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DreamJournalServer).SummarizeDream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DreamJournal_SummarizeDream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DreamJournalServer).SummarizeDream(ctx, req.(*DreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DreamJournal_DreamProphecy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DreamJournalServer).DreamProphecy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DreamJournal_DreamProphecy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DreamJournalServer).DreamProphecy(ctx, req.(*DreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DreamJournal_TagDream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DreamJournalServer).TagDream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DreamJournal_TagDream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DreamJournalServer).TagDream(ctx, req.(*DreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DreamJournal_GetAIInsights_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DreamJournalServer).GetAIInsights(m, &grpc.GenericServerStream[UserRequest, DreamInsight]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DreamJournal_GetAIInsightsServer = grpc.ServerStreamingServer[DreamInsight]

// DreamJournal_ServiceDesc is the grpc.ServiceDesc for DreamJournal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DreamJournal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dreamjournal.DreamJournal",
	HandlerType: (*DreamJournalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _DreamJournal_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _DreamJournal_Login_Handler,
		},
		{
			MethodName: "CreateDream",
			Handler:    _DreamJournal_CreateDream_Handler,
		},
		{
			MethodName: "SummarizeDream",
			Handler:    _DreamJournal_SummarizeDream_Handler,
		},
		{
			MethodName: "DreamProphecy",
			Handler:    _DreamJournal_DreamProphecy_Handler,
		},
		{
			MethodName: "TagDream",
			Handler:    _DreamJournal_TagDream_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDreams",
			Handler:       _DreamJournal_ListDreams_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAIInsights",
			Handler:       _DreamJournal_GetAIInsights_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dream_journal.proto",
}
