# .github/workflows/deploy.yml
name: CI/CD — Deploy to GCE VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DreamJournal    # load env-scoped secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Set up frontend .env
        run: |
          echo "REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}" > frontend/dream-journal/.env

      - name: Check frontend dependencies
        run: |
          cd frontend/dream-journal
          npm ci

      - name: Build frontend
        run: |
          cd frontend/dream-journal
          CI=false npm run build

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.VM_SSH_USER }}@${{ secrets.VM_SSH_HOST }} << 'EOF'
            # Mark the repo as safe for git pulls
            git config --global --add safe.directory /srv/ourdreamjournal

            cd /srv/ourdreamjournal
            git pull origin main

            # Create .env for frontend
            echo "REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}" > frontend/dream-journal/.env

            # Update & restart containers
            docker-compose pull
            docker-compose up -d --build --no-cache

            # Clean up old images
            docker image prune -f
          EOF
